services:
  vsa_docker:
    build:
      context: .
    command: ["sh", "./run.sh"]
    volumes:
      - apps_to_analyze_vsa:/apps_to_analyze/
      - results_vsa:/results/
volumes:
  apps_to_analyze_vsa:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './apps_to_analyze/'
  results_vsa:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './results/'